### ISSUE TITLE
Create marker icons from Cornerwise logo

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#125]
marker-active.png
marker-active@1x.png
marker-active@2x.png
marker-hover.png
marker-hover@1x.png
marker-hover@2x.png
marker-normal.png
marker-normal@1x.png
marker-normal@2x.png

**Comment by danjmoore** [comment]
@brisandbeans do you mean replace all permit sheet icons with 'owl markers'?

**Comment by bdougsand** [comment]
Yeah. Unless you disagree with that.

**Comment by danjmoore** [comment]
I think I should revise the permit markers regardless. I'll see if owlface is a good alternative. I also want to rework the logo so it's easier to tell what it is at smaller sizes.
