### ISSUE TITLE
Write "about" text for intro overlay

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#161]

**Comment by danjmoore** [comment]
<h2>What is Cornerwise?</h2>

<p>Cornerwise is the easiest way to find out what changes are being proposed in your neighboord. This tool was built by <a href="http://www.codeforboston.org">Code for Boston</a> using data from the City’s Planning and Capital Projects departments. Just enter your location and pick one of the proposals on the map to find out what changes might be just around the corner.</p>

<p>If you'd like to learn more or share your opinion about one of these changes, you can contact the <a href="http://www.somervillema.gov/departments/ospcd/planning-and-zoning">Planning and Zoning department</a>, or attend a meeting of the <a href="http://www.somervillema.gov/calendar?field_event_departments_value=Zoning+Board+of+Appeals">Zoning Board of Appeals</a>.</p>

<p><strong>Want to share feedback with the Cornerwise team? Get in touch with us by <a href="mailto:dmoore@somervillema.gov">email.</a></strong></p>

[about-text.txt](https://github.com/cityofsomerville/cornerwise/files/96792/about-text.txt)
