### ISSUE TITLE
Add Link to GitHub Repo

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#167]
Once you've dismissed the intro banner, there's no obvious place to put this link (or the CfB badge, for that matter), so maybe this should wait until we have an about page -- #168.

"File an Issue"? "Fork us on GitHub"?

**Comment by danjmoore** [comment]
Fixed in @brisandbeans commit: https://github.com/cityofsomerville/cornerwise/commit/943b6ef138c96f79bbd85bba29109eee26b8e416
