### ISSUE TITLE
FIlter: Interface for Type Filter

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#17]

**Comment by wrightgd** [comment]
Can you provide more details? Is this more than just PBA vs ZBA filtering?

**Comment by bdougsand** [comment]
I don't have a definitive list of the available permit types, but the ones mentioned in the spreadsheet are:
- SP (special permit)
- Ext
- SP/V (special permit/variance?)
- AA (appeal)
- SPSR (special permit with site plan review)
- V
- Sub/SP (subdivision?)
- Waiver
