### ISSUE TITLE
make it 302 redirect 

### ISSUE THREAD

**Issue by challyed** [cityofsomerville/cornerwise#179]

**Comment by bdougsand** [comment]
http://somervillema.gov/cornerwise currently uses JavaScript to redirect users to the Cornerwise site. For whatever reason, this is not working on some mobile devices. It also means that the user briefly sees the Somerville city website before the redirect.

There may be good reasons for doing it this way, but if not, we should switch to a 30x redirect until we can find a permanent solution.
