### ISSUE TITLE
Permit List: Sorting

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#18]
Based on various criteria

**Comment by wrightgd** [comment]
Should discuss the relative merits of doing this with html tables versus transitioning to DataGrid package.  DG could be overkill.

**Comment by challyed** [comment]
How would we sort the table? is it by Name, Id-number, and Street?
Would this .js help? http://www.kryogenix.org/code/browser/sorttable/

**Comment by wrightgd** [comment]
We may be better using a module that can be integrated with Backbone.js
through require.js.  This would allow us to programmatically sort and
interact with the table from other parts of the application.  Additionally
we wouldn't need to "reinvent the wheel."  One example of such a module
would be backgridjs.

A case could be made for any number of default sort configurations.  I'd
probably favor one that shows the most recently filed permits first.

On Mon, Jul 6, 2015 at 10:59 PM, Edwin Chalumeau notifications@github.com
wrote:

> How would we sort the table? is it by Name, Id-number, and Street?
> Would this .js help? http://www.kryogenix.org/code/browser/sorttable/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cityofsomerville/citydash/issues/18#issuecomment-119056284
> .

## 

George D. Wright
(615) 482-4174

**Comment by wrightgd** [comment]
Read a little more about sorttable.  Maybe I just don't know enough, and integrating it would be easy.  @brisandbeans your thoughts?
