### ISSUE TITLE
Remove blue outline for enter address and go

### ISSUE THREAD

**Issue by challyed** [cityofsomerville/cornerwise#180]

**Comment by danjmoore** [comment]
It's easy to do this with:
     :focus {
     outline: 0;
     }

But I don't think that we should: It does look a lot cleaner, but the blue border (aka focus ring) is an important web accessibility feature built into browsers, and removing it makes it so you can't get around the site via keyboard for those with disabilities and those who just prefer using keyboards. If you hit tab on an accessible site like Github, you'll see the blue outline follows the tab index. Here's some more on it: http://webaim.org/blog/plague-of-outline-0/
