### ISSUE TITLE
Scrape Events Information

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#192]
Record upcoming event names, locations and descriptions. If an event corresponds to a known event (e.g., one extracted from a staff report), add fields.

http://www.somervillema.gov/government/public-minutes

**Comment by kyang01** [comment]
Data is inconsistent across different agenda/event files.

**Comment by kyang01** [comment]
#The agenda and description for event information is inconsistent, so #192 should be closed.
