### ISSUE TITLE
Switch to cube interface

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#205]
http://ux.stackexchange.com/questions/11229/is-this-rotating-cube-interface-user-friendly/11264

**Comment by bdougsand** [comment]
Like, cubes for everything, though.

**Comment by danjmoore** [comment]
Um...is this Web .02 or something? WCAG have established that the spinning cube would be terrible UX, and that the best practice is to use spinning icosahedrons.

**Comment by bdougsand** [comment]
The issues page is a place of business, @danjmoore .
