### ISSUE TITLE
change text of "Explore the data" to "Explore the map"

### ISSUE THREAD

**Issue by mrengy** [cityofsomerville/cornerwise#238]
On the initial view, the text in the bottom of the green bar "Explore the data" allows users to use the map to navigate, but the current text for that link could be made more clear as to what it does. I suggest changing the text to "Explore the map". Other suggestions are welcome.

**Comment by challyed** [comment]
I made the change to "Explore the Map". To me it looks and feels kind of weird but that might be due for me seeing "Explore the Data" more often

**Comment by challyed** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1944704/15878840/4c10a05c-2cec-11e6-9199-5e7f06e4ff36.png)
