### ISSUE TITLE
Mock up notification email

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#240]
The email can contain two sections: one for new permits or capital projects that match the user's subscriptions and another for changes to existing permits/capital projects.

**Comment by challyed** [comment]
#Changes to existing permits/capital projects

Hello $Username,

There has been changes made to the following projects:
$ProjectName $Status $Link

Thanks,
Cornerwise Team

Want to change how you receive these emails?
Update your _settings_ or _unsubscribe_ from this list.

**Comment by challyed** [comment]
#one for new permits or capital projects that match the user's subscription
Hello $Username,

Check out these projects in your area
$ProjectName $ProjectType $Status $Link

Thanks,
Cornerwise Team

Want to change how you receivce these emails?
Update your settings or unsubscribe from this list.

**Comment by danjmoore** [comment]
As a visual jumping-off point...

![screen shot 2016-07-26 at 7-26 4 24 12 pm](https://cloud.githubusercontent.com/assets/9576896/17154077/7e751d02-534d-11e6-90b8-5593942a8e6d.png)

**Comment by mrengy** [comment]
Looks good!

**Comment by danjmoore** [comment]
Has there been discussion on how the mailings will work, as in: do we have a client in mind for installing on Azure? I don't have much experience with templating rich emails but I'd be happy to try

**Comment by challyed** [comment]
Moved to Trello
