### ISSUE TITLE
Update Community Path layer

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#245]
Since the fate of the community path was in question, we're currently not showing it at all. A heavily modified version of the path was approved as part of the GLX redesign.

Could someone work on creating GeoJSON for the new route? You'll need to do some independent research. The current GeoJSON is [here](https://github.com/cityofsomerville/geodata/tree/master/community_path).

Resources:
https://drive.google.com/file/d/0B7qVAVTOJ3PjRmp2eWk4V3pMbTQ/view
http://www.somervillestep.org/green-line-extension-moves-forward-with-conditions/

**Comment by challyed** [comment]
Links to help
- http://www.pathfriends.org/
- http://greenlineextension.eot.state.ma.us/documents/PubMtgs/commPath/communityPath_051414.pdf
- http://www.somervillema.gov/sites/default/files/CommunityPathMap2010.pdf
