### ISSUE TITLE
UI for filtering by multiple cities

### ISSUE THREAD

**Issue by kimkl91c** [cityofsomerville/cornerwise#247]
What if someone wants to see both cambridge and somerville?
<img width="423" alt="screen shot 2016-05-17 at 19 45 00" src="https://cloud.githubusercontent.com/assets/16297012/15343079/e886eada-1c67-11e6-8ef1-1e052d4f071f.png">

**Comment by bdougsand** [comment]
Nope, there's no technical reason why you can't select both. In fact, it's technically [supported](https://www.cornerwise.org/#f.region=somerville%2Ccambridge&fc=1&lat=42.3934808177816&lng=-71.11218452453612&view=main&zoom=14), albeit without a UI.
The UI was thrown together to get some of the hidden features ready for Demo Night. In particular, I wanted some kind of way to show off subscriptions and the fact that Cornerwise can show data from cities other than Somerville. As a result, the interfaces for those features are rudimentary in the extreme. I'm happy to discuss designs.

**Comment by challyed** [comment]
Would it be possible to have a dropdown checkbox list? (If that is a thing and if it is design okay)

**Comment by challyed** [comment]
Moved to Trello
