### ISSUE TITLE
css issue on listing view

### ISSUE THREAD

**Issue by kimkl91c** [cityofsomerville/cornerwise#249]
Two things look wrong with this:
1. "Go to Source" is out of alignment.
2. "Place" word is cut up...

<img width="530" alt="screen shot 2016-06-07 at 20 12 36" src="https://cloud.githubusercontent.com/assets/16297012/15878872/ade75bb8-2cec-11e6-9ea9-abec93cd27cf.png">

**Comment by challyed** [comment]
Moved to trello
