### ISSUE TITLE
Data: Related Documents

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#25]
Items on the [reports and decisions page](http://www.somervillema.gov/departments/planning-board/reports-and-decisions) have links to related documents. It would be nice to get those links as part of the spreadsheet.

**Comment by bdougsand** [comment]
If we're opting to scrape the Reports and Decisions page, we can get the document links that way.

**Comment by danjmoore** [comment]
Per last week's convo, I think we're going to just scrape the R&D page, which will let us keep having links as part of the spreadsheet.
