### ISSUE TITLE
Map icons proportional to map sizing? (just thinking out loud)

### ISSUE THREAD

**Issue by kimkl91c** [cityofsomerville/cornerwise#250]
Do you think we should make icons on map smaller as we zoom out?

<img width="393" alt="screen shot 2016-06-07 at 20 28 19" src="https://cloud.githubusercontent.com/assets/16297012/15879065/94963376-2cee-11e6-9605-04b01a2ab930.png">

<img width="553" alt="screen shot 2016-06-07 at 20 30 28" src="https://cloud.githubusercontent.com/assets/16297012/15879076/b14e1cfe-2cee-11e6-8392-2ce6d1418d60.png">

**Comment by challyed** [comment]
Moved to Trello
