### ISSUE TITLE
New Name

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#27]
Come up with a more fitting name for the project

**Comment by patilav** [comment]
1. Zone Feed
2. Zone Notifier 
3. CityZoner

**Comment by OhRobin** [comment]
4 Zone-ville
5 Somezone

**Comment by OhRobin** [comment]
6 Zoning dashboard

**Comment by OhRobin** [comment]
7 DangerZone
8 DevZone
9 Oh-zone
10 City Change
11 City View

**Comment by danjmoore** [comment]
12 Prospect**us** ... Prospect = extensive view of a landscape, Us = community, and "Prospectus" is also a document that informs stakeholders.

**Comment by danjmoore** [comment]
Drats...www.prospect.us has already been domain squatted...there goes that clever

**Comment by danjmoore** [comment]
13 - I've got it! "CornerWise"...

**Comment by challyed** [comment]
citydash2

**Comment by danjmoore** [comment]
CityDash II: Toyko Drift
