### ISSUE TITLE
Hovering a map icon should apply the permit-hovered css class to the corresponding table row

### ISSUE THREAD

**Issue by wrightgd** [cityofsomerville/cornerwise#32]

**Comment by wrightgd** [comment]
@carrieEgg are there "hover" effects from Bootstrap that we could use on this table?  If so we should phase out our custom CSS in favor of Bootstrap's built-in capabilities.

**Comment by carrieEgg** [comment]
@wrightgd Yep I'm in a process of sorting those things out :)
