### ISSUE TITLE
Refactor map.js to use MarkerView

### ISSUE THREAD

**Issue by wrightgd** [cityofsomerville/cornerwise#33]
Need to implement the concept of a MarkerView to enable clicking/hovering events on leaflet markers.  This stackoverflow post explains the concept, and how to get around the differences of Backbone and Leaflet.

http://stackoverflow.com/questions/14509770/leaflet-markers-from-backbone-js-collection

**Comment by bdougsand** [comment]
I think we ought at some point to refactor map.js into a couple smaller files. I'm marking this issue as closed for now, but we may revisit the idea later.
