### ISSUE TITLE
Create custom marker icons

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#4]
Create a map marker that will be used to represent a "permit".
Create versions of the marker for interaction states: normal, hovered, selected

**Comment by danjmoore** [comment]
![marker-active](https://cloud.githubusercontent.com/assets/9576896/8445709/b72f6580-1f6e-11e5-9dfb-dec5d3d5b789.png)
![marker-hover](https://cloud.githubusercontent.com/assets/9576896/8445710/b73601d8-1f6e-11e5-8c87-3f5bb6f4d42f.png)
![marker-normal](https://cloud.githubusercontent.com/assets/9576896/8445711/b73c1c76-1f6e-11e5-8e72-e051c8c7fa10.png)

**Comment by wrightgd** [comment]
@danjmoore Can these be scaled down? They dominate most of the city at the map's current zoom scale.
