### ISSUE TITLE
Strange scrolling behavior in permits list on selection

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#61]

**Comment by bdougsand** [comment]
Could someone figure out how to consistently reproduce this behavior?

**Comment by patilav** [comment]
Reproduced: 
1. When we first select any of the location it gets stored in some variable 
2. After scrolling and pointing to a new location through the onclick event
3. there is a refresh and render call which sets the scrolling area to the last selected place 
(p.s. couldn't find the exact location for code change though --  permit.js needs to handle the scroll event I guess)
