### ISSUE TITLE
Easy Setup Script

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#64]
Create a Bash script that does the following:
1. If Boot2Docker is installed, spin up the VM (if necessary) and set the appropriate environment variables
2. Check if a 'citydash' image exists AND that it is newer than the latest Dockerfile, then build a new image if necessary. (Docker may take care of this already, so that we can do docker build without having it do [much] extra work.)
3. Start up a new citydash container
4. Open the browser to the appropriate page

**Comment by bdougsand** [comment]
The script works for me, but I'm far from having thoroughly tested it. Could people try it out on their OS X and Linux machines? Run it by cd'ing to your clone of the repo and running `./easystart.sh`. You'll still have to run `manage.py runserver` server once you're connected to the citydash container. I'm debating the most user-friendly approach for doing that automatically.

**Comment by wrightgd** [comment]
I got this:

```
Georges-MacBook-Pro-2:citydash georgewright$ sh easystart.sh
Starting up Boot2Docker.
Waiting for VM and Docker daemon to start...
.....o
Started.
Writing /Users/georgewright/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/georgewright/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/georgewright/.boot2docker/certs/boot2docker-vm/key.pem

To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.59.103:2376
    export DOCKER_CERT_PATH=/Users/georgewright/.boot2docker/certs/boot2docker-vm
    export DOCKER_TLS_VERIFY=1

Or run: `eval "$(boot2docker shellinit)"`

Writing /Users/georgewright/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/georgewright/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/georgewright/.boot2docker/certs/boot2docker-vm/key.pem
Found existing citydash image (created: 2015-07-28T23:34:23)
Dockerfile has changed since the image was created.
Rerun easystart.sh with -b flag to rebuild, -B to ignore changes
```

**Comment by bdougsand** [comment]
The idea is that the script will detect if the Dockerfile or any of the files in docker-support have changed since the local citydash image was created. I guess I could have it default to ignoring the changes and proceed to start up the old image (effectively, default to `./easydash.sh -B`.

**Comment by wrightgd** [comment]
Should I delete my old image and try again? Has a lot changed since the image on my machine was created (last Tues)?

**Comment by bdougsand** [comment]
If you run `./easystart.sh -b`, it _should_ build a new version of the image and run that.

I think the only change to the Dockerfile was my addition of the GDAL utilities like `ogr2ogr` and Redis. Useful, if you want to try exporting Shapefiles to other formats. You can achieve the same effect by doing `apt-get install gdal-bin redis-server`.

There are are also a couple new Python dependencies related to Celery and Redis. They're not essential until we start working on the task queue stuff for running the scraper and notifications. You can install them with `pip install -r /support/requirements.txt`.

Maybe I'll extend the shell script to be more intelligent about how it handles updates. Rebuilding is a pretty crude approach.

**Comment by wrightgd** [comment]
I feel I'm missing something elementary here. I've already gotten the image built on my machine, but I just rebuilt it with ./citydash.sh -b. That script ran, then docker was running. Then I ran `docker run -it -v $PWD/server:/app -p "3000:3000" citydash /bin/bash` and got `bash: docker: command not found`. What am I missing?

**Comment by wrightgd** [comment]
If I open a different terminal window, I get the TLS error...

```
Post http:///var/run/docker.sock/v1.19/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
```

**Comment by bdougsand** [comment]
After you ran `./easystart.sh -b`, it connected to a new citydash container. The `docker` binary exists on your host (OS X) computer, but not inside the Docker container.

**Comment by bdougsand** [comment]
In other words, the easy start script is meant to obviate the need for mucking with `docker` commands. `docker run...` is redundant if you're using the easy start script (if it's working as intended).

**Comment by wrightgd** [comment]
So to clarify, easystart.sh either a) creates the image or b) runs the container if the image is already created? So only one terminal screen would be needed? 
1. run ./easystart.sh
2. within the <i>same</i> terminal window run the command to open the application?

**Comment by bdougsand** [comment]
That's correct. And if you already have a container running, it will connect to that.
