### ISSUE TITLE
Create "Event Point" model in models.py

### ISSUE THREAD

**Issue by wrightgd** [cityofsomerville/cornerwise#65]
Begin models.py by replicating the information we already have attached to permit points on the map.  Generalize the potential use of this model by calling it an "Event" to which someone might want to subscribe to notifications, rather than limiting ourselves to just permits.

**Comment by bdougsand** [comment]
We can discuss terminology. "Event" is a little too generic, I think. I'm thinking "Case"

Fields:
- case number (unique)
- address
- location (django.contrib.gis.db.PointField)
- status
- summary (what we're currently calling description)
- description (longer description)

And probably others, as well.

**Comment by challyed** [comment]
No action needed
