### ISSUE TITLE
Create "Notification zone" model

### ISSUE THREAD

**Issue by wrightgd** [cityofsomerville/cornerwise#67]
This model will allow users to register their preferences for notifications of new event points.  This model will store either a) a point/radius zone or b) a polygon zone, but not both.  Any new event points placed inside a user's notification zone would trigger a notification to that user.

**Comment by bdougsand** [comment]
Sounds good. Do you/how do you think we should handle filters?

**Comment by wrightgd** [comment]
@brisandbeans Filters should be handled in a few different ways, depending on the type of filter:
1. For the unauthenticated user, to display only a subset of Event Points on the map, I would recommend we build this functionality into the REST API for Event Points. When the request is made to the API, it should include a filter parameters JSON object that would tell the API what subset of points to return.
2. For a user to receive notifications about only a subset of points, we could create an Event Category model in Django.  Event Points should have a `django.ForeignKey(Category)` attribute pointing to this model, and a Notification Zone object should have a `django.ManyToManyField(Category)` attribute containing the set of Categories for which a user would like to receive notifications.

**Comment by challyed** [comment]
no action needed
