### ISSUE TITLE
Mockup: User registration

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#68]
Ideally, it will be very easy to transition from the map+filters view to the user registration. 
If the user is not logged in, maybe we can present them with a button that says "Receive Notifications" or "Register for Notifications" (or "Get Updated"; we can tinker with the wording). 
If the user is recognized, we can have a button that says something along the lines of, "Update Notification Preferences" (but better). On the backend, we should allow users to have an arbitrary number of notifications set up, but for the purposes of UI simplicity, let's worry about the common case—i.e., one notification zone.

**Comment by carrieEgg** [comment]
There are several questions I would like to ask...
1. Are users signing up for notification on specific area or permit application or else?
2. Are we going to allow sign-up through social media like Facebook, Google+, and so on..
3. In my perspective there are two types of users:
   - One time user who doesn't want any "user account" set-up. These users prob need only email or phone number, and we would need to embed (?) "stop notification" functionality on email or text message.
   - Long term user who might want to have "user account" set-up. These users prob want to keep track of histories of notification received, reactivate or stop notification, give them choice of getting notified, and so on...

So who are we targeting??

**Comment by wrightgd** [comment]
Here are my thoughts, not that they're the final word...
1. When users look at the map, they can find all the information they want about a specific permit. So I'd propose mainly targeting users who are interested in specific areas.
2. Eventually, yeah, this would be great.
3. I agree, but I'd say we should target "fully registered" users first since that's easiest to do with Django's User model.

**Comment by challyed** [comment]
1.I think it should be by permit
2. Most likely Facebook and Twitter
3. How would be start this process? For setting up a very generic login page. 
Username: Tuser
Password: Password
