### ISSUE TITLE
Create Event Category model

### ISSUE THREAD

**Issue by wrightgd** [cityofsomerville/cornerwise#70]
This model should be referenced by an Event (to categorize it) and by a NotificationZone (to specify which categories result in notifications being generated for that zone. Could probably suffice with a single `category_name=django.CharField()` attribute.

**Comment by wrightgd** [comment]
@brisandbeans I see the javascript label, but I'd nominate this for a python label as well because it needs to be a Django model as well.  How do Django and Backbone models interface with each other?

**Comment by bdougsand** [comment]
That's right. Whoops.

I'm inclined to agree that the `category_name` solution will suffice. No need to overcomplicate things prematurely. Unless we want events to have multiple categories.

I'm not sure yet how much Backbone needs to know about Events.

**Comment by challyed** [comment]
no action needed
