### ISSUE TITLE
Scraper: Stop scraping when the modified date is less than a certain value

### ISSUE THREAD

**Issue by bdougsand** [cityofsomerville/cornerwise#76]
We only want to retrieve updates when scraping Reports and Decisions. Assuming we retrieve a list sorted by modification date (descending), we should scrape only as far as we need to.

**Comment by wrightgd** [comment]
How does the scrape.py script know what the last page of the R&D list is?

**Comment by bdougsand** [comment]
@wrightgd Sorry; I missed this comment until now.

It's a bit inelegant, but I guess scraping always is. It gets the number of the last page by checking the URL of the "Last" link at the bottom of the table.
